// Compiled shader for Windows, Mac, Linux

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Custom/Glass" {
Properties {
 _Color ("Color", Color) = (1.000000,1.000000,1.000000,0.500000)
 _Smoothness ("Smoothness", Range(0.000000,1.000000)) = 0.950000
 _Metallic ("Metallic", Range(0.000000,1.000000)) = 0.000000
 _IOR ("Index of Refraction", Float) = 1.520000
 _Thickness ("Thickness", Float) = 0.100000
 _Distortion ("Distortion", Range(0.000000,1.000000)) = 0.300000
}
SubShader { 
 Tags { "QUEUE"="Transparent" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //        d3d11: 20 math
 // Stats for Fragment shader:
 //        d3d11: 27 math
 Pass {
  Name "Glass"
  Tags { "QUEUE"="Transparent" "RenderType"="Transparent" }
  ZWrite Off
  Blend SrcAlpha OneMinusSrcAlpha
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Vertex shader for "d3d11":
// Stats: 20 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (2160 bytes) on slot 0 {
  Matrix4x4 unity_MatrixV at 1072
  Matrix4x4 unity_MatrixVP at 1264
  Vector3 _WorldSpaceCameraPos at 336
  Vector4 unity_OrthoParams at 400
}
Constant Buffer "UnityPerDraw" (752 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xy          3     NONE   float   xy  
//
      vs_4_0
      dcl_constantbuffer CB0[83], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_input v2.xy
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xy
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[80].xyzw
   5: mad r1.xyzw, cb0[79].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb0[81].xyzw, r0.zzzz, r1.xyzw
   7: add r0.xyz, -r0.xyzx, cb0[21].xyzx
   8: add o0.xyzw, r1.xyzw, cb0[82].xyzw
   9: dp3 r1.x, v1.xyzx, cb1[4].xyzx
  10: dp3 r1.y, v1.xyzx, cb1[5].xyzx
  11: dp3 r1.z, v1.xyzx, cb1[6].xyzx
  12: dp3 r0.w, r1.xyzx, r1.xyzx
  13: max r0.w, r0.w, l(0.000000)
  14: rsq r0.w, r0.w
  15: mul o1.xyz, r0.wwww, r1.xyzx
  16: dp3 r0.w, r0.xyzx, r0.xyzx
  17: rsq r0.w, r0.w
  18: mul r0.xyz, r0.wwww, r0.xyzx
  19: eq r0.w, cb0[25].w, l(0.000000)
  20: movc o2.x, r0.w, r0.x, cb0[67].z
  21: movc o2.y, r0.w, r0.y, cb0[68].z
  22: movc o2.z, r0.w, r0.z, cb0[69].z
  23: mov o3.xy, v2.xyxx
  24: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// Stats: 27 math, 3 temp registers
Set 2D Texture "_CameraFrameTexture" to slot 0

Constant Buffer "$Globals" (2160 bytes) on slot 0 {
  Vector2 _GlobalMipBias at 64
  Vector4 _ScreenParams at 368
  Vector4 _Color at 2112
  Float _Metallic at 2132
  Float _IOR at 2136
  Float _Thickness at 2140
  Float _Distortion at 2144
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xy          3     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[135], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps_siv linear noperspective v0.xy, position
      dcl_input_ps linear v1.xyz
      dcl_input_ps linear v2.xyz
      dcl_output o0.xyzw
      dcl_temps 3
   0: dp3 r0.x, v2.xyzx, v2.xyzx
   1: rsq r0.x, r0.x
   2: mul r0.xyz, r0.xxxx, v2.xyzx
   3: dp3 r0.w, v1.xyzx, v1.xyzx
   4: rsq r0.w, r0.w
   5: mul r1.xyz, r0.wwww, v1.xyzx
   6: dp3 r0.z, r0.xyzx, r1.xyzx
   7: mad r0.w, -r0.z, r0.z, l(1.000000)
   8: div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[133].z
   9: mul r1.w, r1.z, r1.z
  10: mad r0.w, -r1.w, r0.w, l(1.000000)
  11: sqrt r1.w, r0.w
  12: ge r0.w, r0.w, l(0.000000)
  13: mad r1.w, r1.z, r0.z, r1.w
  14: mad r0.z, -r0.z, l(0.300000), l(1.000000)
  15: mul r2.xy, r1.xyxx, r1.wwww
  16: mad r0.xy, r1.zzzz, r0.xyxx, -r2.xyxx
  17: and r0.xy, r0.xyxx, r0.wwww
  18: mad r0.xy, r0.xyxx, cb0[133].wwww, v0.xyxx
  19: div r0.xy, r0.xyxx, cb0[23].xyxx
  20: mad r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
  21: mad r0.xy, r1.xyxx, cb0[134].xxxx, r0.xyxx
  22: sample_b r1.xyzw, r0.xyxx, t0.xyzw, s0, cb0[4].x
  23: add r0.x, -cb0[133].y, l(1.000000)
  24: mul r0.y, cb0[133].y, l(0.800000)
  25: mad r0.xyw, cb0[132].xyxz, r0.xxxx, r0.yyyy
  26: mad r0.xyz, r0.xywx, r0.zzzz, -r1.xyzx
  27: mad o0.xyz, cb0[132].wwww, r0.xyzx, r1.xyzx
  28: mov o0.w, cb0[132].w
  29: ret 
// Approximately 0 instruction slots used


 }
}
Fallback Off
}